web:
  image: nginx
  volumes: 
    - ./dist:/opt/nginx-proxy-history-api/static
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 80:80

app:
  build: ./app
  volumes:
    - ./app:/opt/nginx-proxy-history-api
  ports:
    - 8888:8888
