web:
  image: nginx
  volumes: 
    - ./web/dist:/opt/nginx-proxy-history-api/static
    - ./web/conf/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 80:80

app:
  build: ./docker-images/app
  volumes:
    - ./app:/opt/app
  ports:
    - 8888:8888
