app:
  build: ./app
  volumes:
    - ./app:/opt/nginx-proxy-history-api

web:
  image: nginx
  volumes: 
    - ./dist:/opt/nginx-proxy-history-api/static
    - ./conf/nginx-core.conf:/etc/nginx/nginx.conf
    - ./conf/nginx-app.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 80:80
  links:
    - app
